version: '3.8'

services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb_test"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - test-pgdata:/var/lib/postgresql/data

volumes:
  test-pgdata: 